sudo: false

cache:
  directories:
    - cache/
    
# https://docs.travis-ci.com/user/database-setup/#MySQL
# MySQL binds to 127.0.0.1 and requires authentication. Username “root” and a blank password.

services:
  - mysql
  
script:
  - bash -ex import_database.sh
  # Allow mysql to write into the directory; fix ERROR 1 (HY000)
  - chmod -R 777 .
  - python2.7 generate.py
  - find .
